### ISSUE TITLE
serial and binascii python files

### ISSUE THREAD

**Issue by ADiogoA** [on1arf/jds6600_python#4]
Hi,

Your file is exactly what I was looking for, however i have had problems running it on lines import serial. Where can i find that files?

Sorry the wuestion, i am new on this!

Thank you!

**Comment by on1arf** [comment]
HI AdiagoA,


The question you ask is not directly related to this particular library, 
but is related to python itself.


There is quite some information on the web about python. If you type 
"python import" or "python tutorial" in your preferred search-engine or 
video-website, you should find all the information you need.

E.g. here: 
https://www.youtube.com/results?search_query=python+for+beginners+import+serial


Good luck with learning python :-)


K.

**Comment by ADiogoA** [comment]
Thank you for your advice! I was already able to do it and it works! However I would like to know if with your code is possible to import my own signal to function generator? I can not find out any code line where I can do it.

Thank you in advance!
ADiogoA

**Comment by on1arf** [comment]
Hi,


See api.txt:

---
*** arbitrary waveform operations
arb_getwave(waveid)
     returns the specified arbitrary waveform from memory
         range: 1 - 60

arb_setwave(waveid,wave)
     programs the wave into the arbitrary waveform memory
         range: 1 - 60

     The arbitrary waveform must be formated as a 2048 element list or 
Tuple, containing integer values (range 0 - 4095)

---



Can you give this a try and report if it work OK for you or not?


Kr.

**Comment by ADiogoA** [comment]
Yah! It worked. It is necessary to pre-record the waves in the function generator, but it works!

Thank you a lot!

Best regards
ADiogo
