### ISSUE TITLE
Data parsing problems

### ISSUE THREAD

**Issue by DrBwts** [on1arf/jds6600_python#5]
I ran the example code and ran into some parsing errors straight away. The only helper function that works for me is the `j.getinfo_waveformlist()` which returns all the available waveform modes. For everything else though (even the `set` helper functions) I get variations on the following,

> 
>  File "C:\Users\Research\Documents\JDS6600 sig gen API\jds6600.py", line 192, in __parsedata
>     (one,two)=data.split("=")
> 
> ValueError: not enough values to unpack (expected 2, got 1)
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\Research\Documents\JDS6600 sig gen API\readjds.py", line 20, in <module>
>     j.getinfo_devicetype()
> 
>   File "C:\Users\Research\Documents\JDS6600 sig gen API\jds6600.py", line 476, in getinfo_devicetype
>     return self.__getdata(jds6600.DEVICETYPE)
> 
>   File "C:\Users\Research\Documents\JDS6600 sig gen API\jds6600.py", line 324, in __getdata
>     return self.__getrespondsandparse(reg,n,a)
> 
>   File "C:\Users\Research\Documents\JDS6600 sig gen API\jds6600.py", line 274, in __getrespondsandparse
>     parseddata=self.__parsedata(c_expect,retserial,a)
> 
>   File "C:\Users\Research\Documents\JDS6600 sig gen API\jds6600.py", line 194, in __parsedata
>     raise FormatError("Parsing Returned data: Invalid format, missing \"=\"")
> 
> FormatError: Parsing Returned data: Invalid format, missing "="

No matter which function I call I get the same list of errors. My initial thought was to see what data is being past back but I'm getting strange indentation errors whenever I try to add print statements in to the class code,

`TabError: inconsistent use of tabs and spaces in indentation`

**Comment by DrBwts** [comment]
My bad, I forgot to download the USB drivers. It all work perfectly now , thankyou for the API

**Comment by on1arf** [comment]
Hi,

Yes,
The error indicated that the program expected a reply from the jds6600 
that contains a '=' but that it did not receive that character; so it 
looked like a communication issue between your computer and the JDS.

But I agree that the code can use some more (and better) error-handling 
code :-)


Kr.
